# Generated by Django 3.2.7 on 2021-10-12 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTraining', models.CharField(max_length=50, verbose_name='Название обучения')),
                ('typeOfTraining', models.CharField(max_length=50, verbose_name='Единоразовое/Регулярное')),
                ('dateOfCompletionOfTraining', models.CharField(max_length=50, verbose_name='Дата прохождения обучения')),
                ('dateOfRepeatedPassageOfTraining', models.CharField(blank=True, max_length=50, verbose_name='Дата повторного прохождения обучения')),
            ],
            options={
                'db_table': 'additionalTraining',
            },
        ),
        migrations.CreateModel(
            name='CompulsoryEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfTraining', models.CharField(max_length=50, verbose_name='Название обучения')),
                ('typeOfTraining', models.CharField(max_length=50, verbose_name='Единоразовое/Регулярное')),
                ('dateOfCompletionOfTraining', models.CharField(max_length=50, verbose_name='Дата прохождения обучения')),
                ('dateOfRepeatedPassageOfTraining', models.CharField(blank=True, max_length=50, verbose_name='Дата повторного прохождения обучения')),
            ],
            options={
                'db_table': 'compulsoryEducation',
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documentation/', verbose_name='Документ')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('equipmentPassport', models.FileField(upload_to='equipmentPassport/', verbose_name='Паспорт оборудования')),
                ('dateOfCommissioning', models.DateField(verbose_name='Дата введения в эксплуатацию')),
                ('dateOfTechnicalInspection', models.DateField(verbose_name='Дата проведения тех обследования')),
                ('dateOfPlannedTechnicalInspection', models.DateField(verbose_name='Дата планируемого проведения тех обследования')),
            ],
            options={
                'verbose_name': 'Учет оборудования',
                'verbose_name_plural': 'Учет оборудования',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название товара')),
                ('date', models.DateField(verbose_name='Дата покупки')),
                ('typeOfTesting', models.IntegerField(verbose_name='Срок годности')),
                ('expiration', models.CharField(max_length=50, verbose_name='Период времени')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('price', models.FloatField(max_length=50, verbose_name='Цена')),
                ('cost', models.FloatField(max_length=50, verbose_name='Стоимость')),
                ('invoice', models.FileField(upload_to='invoice/', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Затраты',
                'verbose_name_plural': 'Затрата',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middleName', models.CharField(max_length=50, verbose_name='Отчество')),
                ('fullname', models.CharField(max_length=50, verbose_name='Полное имя')),
                ('birthDate', models.CharField(max_length=50, verbose_name='Дата рождения')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Номер телефона')),
                ('email', models.CharField(max_length=50, verbose_name='Электронная почта')),
                ('dateOfEmployment', models.CharField(max_length=50, verbose_name='Дата трудоустройства')),
                ('structuralDivision', models.CharField(max_length=50, verbose_name='Структурное подразделение')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
                ('heldPost', models.CharField(max_length=50, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название нарушения')),
                ('description', models.TextField(verbose_name='Описание нарушения')),
                ('date', models.CharField(max_length=50, verbose_name='Дата нарушения')),
            ],
            options={
                'verbose_name': 'Нарушение охраны труда',
                'verbose_name_plural': 'Нарушения охраны труда',
            },
        ),
        migrations.CreateModel(
            name='Testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfTesting', models.CharField(max_length=50, verbose_name='Вид тестирования')),
                ('date', models.DateField(verbose_name='Дата тестирования')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Testing', to='main.personnel')),
            ],
            options={
                'verbose_name': 'Тестирования',
                'verbose_name_plural': 'Тестирование',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOfTesting', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата выдачи')),
                ('department', models.CharField(max_length=50, verbose_name='Отдел')),
                ('expenses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Orders', to='main.expenses')),
                ('personnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Orders', to='main.personnel')),
            ],
            options={
                'verbose_name': 'Заказы',
                'verbose_name_plural': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='MedicalExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfMedicalExamination', models.DateField(max_length=50, verbose_name='Дата прохождения медосмотра')),
                ('dateOfRepeatedMedicalExamination', models.DateField(max_length=50, verbose_name='Дата повторного прохождения медосмотра')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MedicalExamination', to='main.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='InjuryAccounting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название травмы')),
                ('description', models.TextField(verbose_name='Описание травмы')),
                ('date', models.DateField(verbose_name='Дата происшествия')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='InjuryAccounting', to='main.personnel')),
            ],
            options={
                'verbose_name': 'Учет травм',
                'verbose_name_plural': 'Учет травм',
            },
        ),
        migrations.CreateModel(
            name='CompulsoryEducationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('compulsoryEducation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompulsoryEducationFile', to='main.compulsoryeducation')),
            ],
        ),
        migrations.AddField(
            model_name='compulsoryeducation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CompulsoryEducation', to='main.personnel'),
        ),
        migrations.CreateModel(
            name='AdditionalTrainingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('additionalTraining', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdditionalTrainingFile', to='main.additionaltraining')),
            ],
        ),
        migrations.AddField(
            model_name='additionaltraining',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='AdditionalTraining', to='main.personnel'),
        ),
    ]
